//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEDOC.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbDocSubido
    {
        public int numTotalSub { get; set; }
        public string nombredSub { get; set; }
        public string detalledSub { get; set; }
        public int numConseSub { get; set; }
        public int idCliente { get; set; }
        public string referenciaSub { get; set; }
        public int idUsuario { get; set; }
        public System.DateTime fechaSub { get; set; }
        public byte[] documentoWordSub { get; set; }
        public byte[] documentoPdfSub { get; set; }
        public int idProyecto { get; set; }
        public string periodo { get; set; }
        public string ModificadoPor { get; set; }
        public string nombrerealWordSub { get; set; }
        public string nombrerealPdfSub { get; set; }
    
        public virtual TbDocSubido TbDocSubido1 { get; set; }
        public virtual TbDocSubido TbDocSubido2 { get; set; }
    }
}
