//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEDOC.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbDocCreado
    {
        public int numtotaldocu { get; set; }
        public string nombredCreado { get; set; }
        public string asuntodCreado { get; set; }
        public string detalledCreadol { get; set; }
        public string Usuario { get; set; }
        public int idProyecto { get; set; }
        public int numConsecu { get; set; }
        public byte[] documentoPDF { get; set; }
        public byte[] documentoWord { get; set; }
        public string estatus { get; set; }
        public System.DateTime fecha { get; set; }
        public int idCliente { get; set; }
        public string periodo { get; set; }
        public string numReferencia { get; set; }
        public int habilitado { get; set; }
        public string modificadoPor { get; set; }
        public string nombrereal { get; set; }
        public string nombrealpdf { get; set; }
    }
}
